//GLSL version to use
#version 460

//size of a workgroup for compute
layout (local_size_x = 16, local_size_y = 16) in;

//descriptor bindings for the pipeline
layout(rgba16f,set = 0, binding = 0) uniform image2D image;

// push constant
layout( push_constant ) uniform constants
{
 vec4 colorStart;
 vec4 colorEnd;
 vec4 data3;
 vec4 data4;
};

void main() 
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(image);

    if(texelCoord.x < size.x && texelCoord.y < size.y)
    {
        vec4 outColor = mix(colorStart, colorEnd, gl_LocalInvocationID.x / 16.0f);    
        imageStore(image, texelCoord, outColor);
    }
}